version: "3"

services:
  discord-musicbot:
    build: .
    image: discord-musicbot:latest
    container_name: discord-musicbot
    restart: unless-stopped
    environment:
      - token=${DISCORD_TOKEN}
      - clientId=${DISCORD_CLIENT_ID}
      - clientSecret=${DISCORD_CLIENT_SECRET}
    ports:
      - "127.0.0.1:3033:80"
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    volumes:
      - ./config.js:/usr/src/app/config.js:ro

  lavalink:
    image: fredboat/lavalink:dev
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    expose:
      - "3035"
    networks:
      - lavalink-net
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro

networks:
  lavalink-net:
