version: "3"

services:
  rawon-musicbot:
    build: .
    image: rawon-musicbot:latest
    container_name: rawon-musicbot
    restart: unless-stopped
    ports:
      - "127.0.0.1:3033:80"
    volumes:
      - ./.env:/usr/src/app/.env
