version: "3"

services:
  rawon-musicbot:
    build: .
    env_file: .env
    image: rawon-musicbot:latest
    container_name: rawon-musicbot
    ports:
      - "127.0.0.1:3033:80"
    environment:
      - DOTENV_CONFIG_DEBUG=true
      - DOTENV_CONFIG_PATH=/usr/src/app/.env
      - NODE_ENV=production
      - NODE_OPTIONS=--experimental-specifier-resolution=node
      - CI=true
      - DISCORD_TOKEN=${DISCORD_TOKEN-""}
    volumes:
      - ./.rawon.env:/usr/src/app/.env:ro
